# Generated by Django 6.0 on 2025-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
