# Generated by Django 6.0 on 2025-12-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='needs.need'),
        ),
    ]
